version: "3"
services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5051:5050
    networks:
      - api-network
  app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5052:5050
    networks:
      - api-network
  app-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5053:5050
    networks:
      - api-network
  load-balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
