name: Integration Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 8080:8080
          - 5051:5051
          - 5052:5052
          - 5053:5053

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.28.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Build and start services
        run: docker compose -f docker/docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: |
          sleep 30
          docker compose ps

      - name: Run integration tests
        run: |
          # Run your tests here. For example, using curl to hit the load balancer endpoint.
          curl 'http://localhost:8080/service-info' | jq .

      - name: Shut down services
        if: always()
        run: just docker-down
