# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Check test coverage
        run: |
          just pytest -vv

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main'}}
    needs: build
    environment: production

    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -s ${{ secrets.RENDER_DEPLOY_HOOK }} \
            -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY"
